apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: tomcat-deployment
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: testapp
    spec:
      containers:
      - name: testapp
        image: tomcat
        ports:
        - containerPort: 8080
---
kind: Service
apiVersion: v1
metadata:
  name: tomcat
spec:
  selector:
    app: testapp
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
